
package com.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-06-09T15:16:24.234+08:00
 * Generated source version: 3.0.3
 * 
 */
public final class TransAuthorityFromEDOCToGEMS_TransAuthorityFromEDOCToGEMSSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/TransAuthorityFromEDOCToGEMS/", "TransAuthorityFromEDOCToGEMS");

    private TransAuthorityFromEDOCToGEMS_TransAuthorityFromEDOCToGEMSSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TransAuthorityFromEDOCToGEMS_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TransAuthorityFromEDOCToGEMS_Service ss = new TransAuthorityFromEDOCToGEMS_Service(wsdlURL, SERVICE_NAME);
        TransAuthorityFromEDOCToGEMS port = ss.getTransAuthorityFromEDOCToGEMSSOAP();  
        
        {
        System.out.println("Invoking getAuth...");
        InType _getAuth_in = new InType();
        _getAuth_in.setDocNo("GECW15060000001");
        _getAuth_in.setGemsToken("0eb3ef12af834058a32e6dd671e88ab7");
        _getAuth_in.setEdocToken("");
        long _getAuth__return = port.getAuth(_getAuth_in);
        System.out.println("getAuth.result=" + _getAuth__return);


        }
        {
        System.out.println("Invoking updateImageStatus...");
        java.util.List<InputType> _updateImageStatus_in = new ArrayList<InputType>();;
        InputType _inputType = new InputType();
        _inputType.setDocNo("GECV15050000023");
        _inputType.setBusinessType("-1");
        _inputType.setBusinessTypeCode("-1");
        _inputType.setEdocToken("");
        _inputType.setGemsToken("");
        _inputType.setImageStatus("2");
        _inputType.setUserId("-1");
        _inputType.setUserName("-1");
        _updateImageStatus_in.add(_inputType);
        java.lang.String _updateImageStatus__return = port.updateImageStatus(_updateImageStatus_in);
        System.out.println("updateImageStatus.result=" + _updateImageStatus__return);


        }

        System.exit(0);
    }

}
