package com.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-06-09T15:16:24.321+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://www.example.org/TransAuthorityFromEDOCToGEMS/", name = "TransAuthorityFromEDOCToGEMS")
@XmlSeeAlso({ObjectFactory.class})
public interface TransAuthorityFromEDOCToGEMS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAuth", targetNamespace = "http://www.example.org/TransAuthorityFromEDOCToGEMS/", className = "com.GetAuth")
    @WebMethod(action = "http://www.example.org/TransAuthorityFromEDOCToGEMS/getAuth")
    @ResponseWrapper(localName = "getAuthResponse", targetNamespace = "http://www.example.org/TransAuthorityFromEDOCToGEMS/", className = "com.GetAuthResponse")
    public long getAuth(
        @WebParam(name = "in", targetNamespace = "")
        com.client.InType in
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateImageStatus", targetNamespace = "http://www.example.org/TransAuthorityFromEDOCToGEMS/", className = "com.UpdateImageStatus")
    @WebMethod(action = "http://www.example.org/TransAuthorityFromEDOCToGEMS/updateImageStatus")
    @ResponseWrapper(localName = "updateImageStatusResponse", targetNamespace = "http://www.example.org/TransAuthorityFromEDOCToGEMS/", className = "com.UpdateImageStatusResponse")
    public java.lang.String updateImageStatus(
        @WebParam(name = "in", targetNamespace = "")
        java.util.List<com.client.InputType> in
    );
}
